tables.exclude.file.path=classpath:exclude_tables.txt
batch.read.size=${READ_BATCH_SIZE:1000}
batch.write.size=${WRITE_BATCH_SIZE:250}
thread.count=${THREAD_COUNT}
retry.failed.items=${RETRY_FAILED_ITEMS:false}

spring.datasource.source.jdbcUrl=${SOURCE_DB_URL}
spring.datasource.source.username=${SOURCE_DB_USERNAME}
spring.datasource.source.password=${SOURCE_DB_PASSWORD}
spring.datasource.source.maximum-pool-size=${MAX_CONN_POOL_SIZE}

spring.datasource.sink.jdbcUrl=${SINK_DB_URL}
spring.datasource.sink.username=${SINK_DB_USERNAME}
spring.datasource.sink.password=${SINK_DB_PASSWORD}
spring.datasource.sink.maximum-pool-size=${MAX_CONN_POOL_SIZE}

spring.batch.jdbc.initialize-schema=always
spring.datasource.batch.jdbcUrl=${MGT_DB_URL}
spring.datasource.batch.username=${MGT_DB_USERNAME}
spring.datasource.batch.password=${MGT_DB_PASSWORD}
spring.datasource.batch.maximum-pool-size=${MAX_CONN_POOL_SIZE}

logging.config=${LOG_CFG_FILE:classpath:default-logback.xml}
