tables.exclude.file.path=classpath:exclude_tables.txt
batch.read.size=${READ_BATCH_SIZE:1000}
batch.write.size=${WRITE_BATCH_SIZE:1000}
thread.count=${THREAD_COUNT}
retry.failed.items=${RETRY_FAILED_ITEMS:false}
connection.max.pool.size=${MAX_CONN_POOL_SIZE:}

spring.datasource.source.jdbcUrl=${SOURCE_DB_URL}
spring.datasource.source.username=${SOURCE_DB_USERNAME}
spring.datasource.source.password=${SOURCE_DB_PASSWORD}

spring.datasource.sink.jdbcUrl=${SINK_DB_URL}
spring.datasource.sink.username=${SINK_DB_USERNAME}
spring.datasource.sink.password=${SINK_DB_PASSWORD}

spring.batch.jdbc.initialize-schema=always
spring.datasource.mgt.jdbcUrl=${MGT_DB_URL}
spring.datasource.mgt.username=${MGT_DB_USERNAME}
spring.datasource.mgt.password=${MGT_DB_PASSWORD}

logging.config=${LOG_CFG_FILE:classpath:default-logback.xml}
