SET FOREIGN_KEY_CHECKS=0;
    
CREATE TABLE `person` (
    `person_id` int NOT NULL AUTO_INCREMENT,
    `gender` varchar(50) DEFAULT '',
    `birthdate` date DEFAULT NULL,
    `birthdate_estimated` tinyint(1) NOT NULL DEFAULT '0',
    `dead` tinyint(1) NOT NULL DEFAULT '0',
    `death_date` datetime DEFAULT NULL,
    `cause_of_death` int DEFAULT NULL,
    `creator` int DEFAULT NULL,
    `date_created` datetime NOT NULL,
    `changed_by` int DEFAULT NULL,
    `date_changed` datetime DEFAULT NULL,
    `voided` tinyint(1) NOT NULL DEFAULT '0',
    `voided_by` int DEFAULT NULL,
    `date_voided` datetime DEFAULT NULL,
    `void_reason` varchar(255) DEFAULT NULL,
    `uuid` char(38) NOT NULL,
    `deathdate_estimated` tinyint(1) NOT NULL DEFAULT '0',
    `birthtime` time DEFAULT NULL,
    PRIMARY KEY (`person_id`),
    UNIQUE KEY `person_uuid_index` (`uuid`),
    KEY `person_birthdate` (`birthdate`),
    KEY `person_death_date` (`death_date`),
    KEY `person_died_because` (`cause_of_death`),
    KEY `user_who_changed_person` (`changed_by`),
    KEY `user_who_created_person` (`creator`),
    KEY `user_who_voided_person` (`voided_by`),
    CONSTRAINT `person_died_because` FOREIGN KEY (`cause_of_death`) REFERENCES `concept` (`concept_id`),
    CONSTRAINT `user_who_changed_person` FOREIGN KEY (`changed_by`) REFERENCES `users` (`user_id`),
    CONSTRAINT `user_who_created_person` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`),
    CONSTRAINT `user_who_voided_person` FOREIGN KEY (`voided_by`) REFERENCES `users` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb3;

CREATE TABLE `users` (
    `user_id` int NOT NULL AUTO_INCREMENT,
    `system_id` varchar(50) NOT NULL DEFAULT '',
    `username` varchar(50) DEFAULT NULL,
    `password` varchar(128) DEFAULT NULL,
    `salt` varchar(128) DEFAULT NULL,
    `secret_question` varchar(255) DEFAULT NULL,
    `secret_answer` varchar(255) DEFAULT NULL,
    `creator` int NOT NULL DEFAULT '0',
    `date_created` datetime NOT NULL,
    `changed_by` int DEFAULT NULL,
    `date_changed` datetime DEFAULT NULL,
    `person_id` int NOT NULL,
    `retired` tinyint(1) NOT NULL DEFAULT '0',
    `retired_by` int DEFAULT NULL,
    `date_retired` datetime DEFAULT NULL,
    `retire_reason` varchar(255) DEFAULT NULL,
    `uuid` char(38) NOT NULL,
    PRIMARY KEY (`user_id`),
    UNIQUE KEY `uuid_uk` (`uuid`),
    KEY `user_who_changed_user` (`changed_by`),
    KEY `user_creator` (`creator`),
    KEY `user_who_retired_this_user` (`retired_by`),
    KEY `person_id_for_user` (`person_id`),
    CONSTRAINT `person_id_for_user` FOREIGN KEY (`person_id`) REFERENCES `person` (`person_id`),
    CONSTRAINT `user_creator` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`),
    CONSTRAINT `user_who_changed_user` FOREIGN KEY (`changed_by`) REFERENCES `users` (`user_id`),
    CONSTRAINT `user_who_retired_this_user` FOREIGN KEY (`retired_by`) REFERENCES `users` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb3;

CREATE TABLE `privilege` (
    `privilege` varchar(255) NOT NULL,
    `description` text,
    `uuid` char(38) NOT NULL,
    PRIMARY KEY (`privilege`),
    UNIQUE KEY `privilege_uuid_index` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `role` (
    `role` varchar(50) NOT NULL DEFAULT '',
    `description` varchar(255) DEFAULT NULL,
    `uuid` char(38) NOT NULL,
    PRIMARY KEY (`role`),
    UNIQUE KEY `role_uuid_index` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `user_role` (
    `user_id` int NOT NULL DEFAULT '0',
    `role` varchar(50) NOT NULL DEFAULT '',
    PRIMARY KEY (`role`,`user_id`),
    KEY `user_role_to_users` (`user_id`),
    CONSTRAINT `role_definitions` FOREIGN KEY (`role`) REFERENCES `role` (`role`),
    CONSTRAINT `user_role_to_users` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `user_property` (
    `user_id` int NOT NULL DEFAULT '0',
    `property` varchar(100) NOT NULL DEFAULT '',
    `property_value` text,
    PRIMARY KEY (`user_id`,`property`),
    CONSTRAINT `user_property_to_users` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `concept_class` (
    `concept_class_id` int NOT NULL AUTO_INCREMENT,
    `name` varchar(255) NOT NULL DEFAULT '',
    `description` varchar(255) DEFAULT NULL,
    `creator` int NOT NULL DEFAULT '0',
    `date_created` datetime NOT NULL,
    `retired` tinyint(1) NOT NULL DEFAULT '0',
    `retired_by` int DEFAULT NULL,
    `date_retired` datetime DEFAULT NULL,
    `retire_reason` varchar(255) DEFAULT NULL,
    `uuid` char(38) NOT NULL,
    `date_changed` datetime DEFAULT NULL,
    `changed_by` int DEFAULT NULL,
    PRIMARY KEY (`concept_class_id`),
    UNIQUE KEY `concept_class_uuid_index` (`uuid`),
    KEY `concept_class_retired_status` (`retired`),
    KEY `concept_class_creator` (`creator`),
    KEY `user_who_retired_concept_class` (`retired_by`),
    KEY `concept_class_name_index` (`name`),
    KEY `concept_class_changed_by` (`changed_by`),
    CONSTRAINT `concept_class_changed_by` FOREIGN KEY (`changed_by`) REFERENCES `users` (`user_id`),
    CONSTRAINT `concept_class_creator` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`),
    CONSTRAINT `user_who_retired_concept_class` FOREIGN KEY (`retired_by`) REFERENCES `users` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb3;

CREATE TABLE `concept_datatype` (
    `concept_datatype_id` int NOT NULL AUTO_INCREMENT,
    `name` varchar(255) NOT NULL DEFAULT '',
    `hl7_abbreviation` varchar(3) DEFAULT NULL,
    `description` varchar(255) DEFAULT NULL,
    `creator` int NOT NULL DEFAULT '0',
    `date_created` datetime NOT NULL,
    `retired` tinyint(1) NOT NULL DEFAULT '0',
    `retired_by` int DEFAULT NULL,
    `date_retired` datetime DEFAULT NULL,
    `retire_reason` varchar(255) DEFAULT NULL,
    `uuid` char(38) NOT NULL,
    PRIMARY KEY (`concept_datatype_id`),
    UNIQUE KEY `concept_datatype_uuid_index` (`uuid`),
    KEY `concept_datatype_retired_status` (`retired`),
    KEY `concept_datatype_creator` (`creator`),
    KEY `user_who_retired_concept_datatype` (`retired_by`),
    KEY `concept_datatype_name_index` (`name`),
    CONSTRAINT `concept_datatype_creator` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`),
    CONSTRAINT `user_who_retired_concept_datatype` FOREIGN KEY (`retired_by`) REFERENCES `users` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb3;

CREATE TABLE `concept` (
    `concept_id` int NOT NULL AUTO_INCREMENT,
    `retired` tinyint(1) NOT NULL DEFAULT '0',
    `short_name` varchar(255) DEFAULT NULL,
    `description` text,
    `form_text` text,
    `datatype_id` int NOT NULL DEFAULT '0',
    `class_id` int NOT NULL DEFAULT '0',
    `is_set` tinyint(1) NOT NULL DEFAULT '0',
    `creator` int NOT NULL DEFAULT '0',
    `date_created` datetime NOT NULL,
    `version` varchar(50) DEFAULT NULL,
    `changed_by` int DEFAULT NULL,
    `date_changed` datetime DEFAULT NULL,
    `retired_by` int DEFAULT NULL,
    `date_retired` datetime DEFAULT NULL,
    `retire_reason` varchar(255) DEFAULT NULL,
    `uuid` char(38) NOT NULL,
    PRIMARY KEY (`concept_id`),
    UNIQUE KEY `concept_uuid_index` (`uuid`),
    KEY `user_who_changed_concept` (`changed_by`),
    KEY `concept_classes` (`class_id`),
    KEY `concept_creator` (`creator`),
    KEY `concept_datatypes` (`datatype_id`),
    KEY `user_who_retired_concept` (`retired_by`),
    CONSTRAINT `concept_classes` FOREIGN KEY (`class_id`) REFERENCES `concept_class` (`concept_class_id`),
    CONSTRAINT `concept_creator` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`),
    CONSTRAINT `concept_datatypes` FOREIGN KEY (`datatype_id`) REFERENCES `concept_datatype` (`concept_datatype_id`),
    CONSTRAINT `user_who_changed_concept` FOREIGN KEY (`changed_by`) REFERENCES `users` (`user_id`),
    CONSTRAINT `user_who_retired_concept` FOREIGN KEY (`retired_by`) REFERENCES `users` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb3;

CREATE TABLE `patient` (
    `patient_id` int NOT NULL,
    `creator` int NOT NULL DEFAULT '0',
    `date_created` datetime NOT NULL,
    `changed_by` int DEFAULT NULL,
    `date_changed` datetime DEFAULT NULL,
    `voided` tinyint(1) NOT NULL DEFAULT '0',
    `voided_by` int DEFAULT NULL,
    `date_voided` datetime DEFAULT NULL,
    `void_reason` varchar(255) DEFAULT NULL,
    `allergy_status` varchar(50) NOT NULL DEFAULT 'Unknown',
    PRIMARY KEY (`patient_id`),
    KEY `user_who_changed_pat` (`changed_by`),
    KEY `user_who_created_patient` (`creator`),
    KEY `user_who_voided_patient` (`voided_by`),
    CONSTRAINT `person_id_for_patient` FOREIGN KEY (`patient_id`) REFERENCES `person` (`person_id`) ON UPDATE CASCADE,
    CONSTRAINT `user_who_changed_pat` FOREIGN KEY (`changed_by`) REFERENCES `users` (`user_id`),
    CONSTRAINT `user_who_created_patient` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`),
    CONSTRAINT `user_who_voided_patient` FOREIGN KEY (`voided_by`) REFERENCES `users` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `visit_type` (
    `visit_type_id` int NOT NULL AUTO_INCREMENT,
    `name` varchar(255) NOT NULL,
    `description` varchar(1024) DEFAULT NULL,
    `creator` int NOT NULL,
    `date_created` datetime NOT NULL,
    `changed_by` int DEFAULT NULL,
    `date_changed` datetime DEFAULT NULL,
    `retired` tinyint(1) NOT NULL DEFAULT '0',
    `retired_by` int DEFAULT NULL,
    `date_retired` datetime DEFAULT NULL,
    `retire_reason` varchar(255) DEFAULT NULL,
    `uuid` char(38) NOT NULL,
    PRIMARY KEY (`visit_type_id`),
    UNIQUE KEY `uuid` (`uuid`),
    KEY `visit_type_creator` (`creator`),
    KEY `visit_type_changed_by` (`changed_by`),
    KEY `visit_type_retired_by` (`retired_by`),
    CONSTRAINT `visit_type_changed_by` FOREIGN KEY (`changed_by`) REFERENCES `users` (`user_id`),
    CONSTRAINT `visit_type_creator` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`),
    CONSTRAINT `visit_type_retired_by` FOREIGN KEY (`retired_by`) REFERENCES `users` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb3;

CREATE TABLE `location` (
    `location_id` int NOT NULL AUTO_INCREMENT,
    `name` varchar(255) NOT NULL DEFAULT '',
    `description` varchar(255) DEFAULT NULL,
    `address1` varchar(255) DEFAULT NULL,
    `address2` varchar(255) DEFAULT NULL,
    `city_village` varchar(255) DEFAULT NULL,
    `state_province` varchar(255) DEFAULT NULL,
    `postal_code` varchar(50) DEFAULT NULL,
    `country` varchar(50) DEFAULT NULL,
    `latitude` varchar(50) DEFAULT NULL,
    `longitude` varchar(50) DEFAULT NULL,
    `creator` int NOT NULL DEFAULT '0',
    `date_created` datetime NOT NULL,
    `county_district` varchar(255) DEFAULT NULL,
    `address3` varchar(255) DEFAULT NULL,
    `address4` varchar(255) DEFAULT NULL,
    `address5` varchar(255) DEFAULT NULL,
    `address6` varchar(255) DEFAULT NULL,
    `retired` tinyint(1) NOT NULL DEFAULT '0',
    `retired_by` int DEFAULT NULL,
    `date_retired` datetime DEFAULT NULL,
    `retire_reason` varchar(255) DEFAULT NULL,
    `parent_location` int DEFAULT NULL,
    `uuid` char(38) NOT NULL,
    `changed_by` int DEFAULT NULL,
    `date_changed` datetime DEFAULT NULL,
    `address7` varchar(255) DEFAULT NULL,
    `address8` varchar(255) DEFAULT NULL,
    `address9` varchar(255) DEFAULT NULL,
    `address10` varchar(255) DEFAULT NULL,
    `address11` varchar(255) DEFAULT NULL,
    `address12` varchar(255) DEFAULT NULL,
    `address13` varchar(255) DEFAULT NULL,
    `address14` varchar(255) DEFAULT NULL,
    `address15` varchar(255) DEFAULT NULL,
    PRIMARY KEY (`location_id`),
    UNIQUE KEY `location_uuid_index` (`uuid`),
    KEY `name_of_location` (`name`),
    KEY `location_retired_status` (`retired`),
    KEY `user_who_created_location` (`creator`),
    KEY `user_who_retired_location` (`retired_by`),
    KEY `parent_location` (`parent_location`),
    KEY `location_changed_by` (`changed_by`),
    CONSTRAINT `location_changed_by` FOREIGN KEY (`changed_by`) REFERENCES `users` (`user_id`),
    CONSTRAINT `parent_location` FOREIGN KEY (`parent_location`) REFERENCES `location` (`location_id`),
    CONSTRAINT `user_who_created_location` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`),
    CONSTRAINT `user_who_retired_location` FOREIGN KEY (`retired_by`) REFERENCES `users` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb3;

CREATE TABLE `visit` (
    `visit_id` int NOT NULL AUTO_INCREMENT,
    `patient_id` int NOT NULL,
    `visit_type_id` int NOT NULL,
    `date_started` datetime NOT NULL,
    `date_stopped` datetime DEFAULT NULL,
    `indication_concept_id` int DEFAULT NULL,
    `location_id` int DEFAULT NULL,
    `creator` int NOT NULL,
    `date_created` datetime NOT NULL,
    `changed_by` int DEFAULT NULL,
    `date_changed` datetime DEFAULT NULL,
    `voided` tinyint(1) NOT NULL DEFAULT '0',
    `voided_by` int DEFAULT NULL,
    `date_voided` datetime DEFAULT NULL,
    `void_reason` varchar(255) DEFAULT NULL,
    `uuid` char(38) NOT NULL,
    PRIMARY KEY (`visit_id`),
    UNIQUE KEY `uuid` (`uuid`),
    KEY `visit_patient_index` (`patient_id`),
    KEY `visit_type_fk` (`visit_type_id`),
    KEY `visit_location_fk` (`location_id`),
    KEY `visit_creator_fk` (`creator`),
    KEY `visit_voided_by_fk` (`voided_by`),
    KEY `visit_changed_by_fk` (`changed_by`),
    KEY `visit_indication_concept_fk` (`indication_concept_id`),
    KEY `visit_date_stopped` (`date_stopped`),
    KEY `idx_visit_patient_id_voided` (`patient_id`,`voided`),
    KEY `idx_visit_location_id_date_stopped` (`location_id`,`date_stopped`),
    CONSTRAINT `visit_changed_by_fk` FOREIGN KEY (`changed_by`) REFERENCES `users` (`user_id`),
    CONSTRAINT `visit_creator_fk` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`),
    CONSTRAINT `visit_indication_concept_fk` FOREIGN KEY (`indication_concept_id`) REFERENCES `concept` (`concept_id`),
    CONSTRAINT `visit_location_fk` FOREIGN KEY (`location_id`) REFERENCES `location` (`location_id`),
    CONSTRAINT `visit_patient_fk` FOREIGN KEY (`patient_id`) REFERENCES `patient` (`patient_id`),
    CONSTRAINT `visit_type_fk` FOREIGN KEY (`visit_type_id`) REFERENCES `visit_type` (`visit_type_id`),
    CONSTRAINT `visit_voided_by_fk` FOREIGN KEY (`voided_by`) REFERENCES `users` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb3;

CREATE TABLE `encounter_type` (
    `encounter_type_id` int NOT NULL AUTO_INCREMENT,
    `name` varchar(50) NOT NULL DEFAULT '',
    `description` text,
    `creator` int NOT NULL DEFAULT '0',
    `date_created` datetime NOT NULL,
    `retired` tinyint(1) NOT NULL DEFAULT '0',
    `retired_by` int DEFAULT NULL,
    `date_retired` datetime DEFAULT NULL,
    `retire_reason` varchar(255) DEFAULT NULL,
    `uuid` char(38) NOT NULL,
    `edit_privilege` varchar(255) DEFAULT NULL,
    `view_privilege` varchar(255) DEFAULT NULL,
    `changed_by` int DEFAULT NULL,
    `date_changed` datetime DEFAULT NULL,
    PRIMARY KEY (`encounter_type_id`),
    UNIQUE KEY `encounter_type_unique_name` (`name`),
    UNIQUE KEY `encounter_type_uuid_index` (`uuid`),
    KEY `encounter_type_retired_status` (`retired`),
    KEY `user_who_created_type` (`creator`),
    KEY `user_who_retired_encounter_type` (`retired_by`),
    KEY `privilege_which_can_view_encounter_type` (`view_privilege`),
    KEY `privilege_which_can_edit_encounter_type` (`edit_privilege`),
    KEY `encounter_type_changed_by` (`changed_by`),
    CONSTRAINT `encounter_type_changed_by` FOREIGN KEY (`changed_by`) REFERENCES `users` (`user_id`),
    CONSTRAINT `privilege_which_can_edit_encounter_type` FOREIGN KEY (`edit_privilege`) REFERENCES `privilege` (`privilege`),
    CONSTRAINT `privilege_which_can_view_encounter_type` FOREIGN KEY (`view_privilege`) REFERENCES `privilege` (`privilege`),
    CONSTRAINT `user_who_created_type` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`),
    CONSTRAINT `user_who_retired_encounter_type` FOREIGN KEY (`retired_by`) REFERENCES `users` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb3;

CREATE TABLE `form` (
    `form_id` int NOT NULL AUTO_INCREMENT,
    `name` varchar(255) NOT NULL DEFAULT '',
    `version` varchar(50) NOT NULL DEFAULT '',
    `build` int DEFAULT NULL,
    `published` tinyint(1) NOT NULL DEFAULT '0',
    `xslt` text,
    `template` text,
    `description` text,
    `encounter_type` int DEFAULT NULL,
    `creator` int NOT NULL DEFAULT '0',
    `date_created` datetime NOT NULL,
    `changed_by` int DEFAULT NULL,
    `date_changed` datetime DEFAULT NULL,
    `retired` tinyint(1) NOT NULL DEFAULT '0',
    `retired_by` int DEFAULT NULL,
    `date_retired` datetime DEFAULT NULL,
    `retired_reason` varchar(255) DEFAULT NULL,
    `uuid` char(38) NOT NULL,
    PRIMARY KEY (`form_id`),
    UNIQUE KEY `form_uuid_index` (`uuid`),
    KEY `form_published_index` (`published`),
    KEY `form_retired_index` (`retired`),
    KEY `form_published_and_retired_index` (`published`,`retired`),
    KEY `user_who_last_changed_form` (`changed_by`),
    KEY `user_who_created_form` (`creator`),
    KEY `form_encounter_type` (`encounter_type`),
    KEY `user_who_retired_form` (`retired_by`),
    CONSTRAINT `form_encounter_type` FOREIGN KEY (`encounter_type`) REFERENCES `encounter_type` (`encounter_type_id`),
    CONSTRAINT `user_who_created_form` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`),
    CONSTRAINT `user_who_last_changed_form` FOREIGN KEY (`changed_by`) REFERENCES `users` (`user_id`),
    CONSTRAINT `user_who_retired_form` FOREIGN KEY (`retired_by`) REFERENCES `users` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb3;

CREATE TABLE `encounter` (
    `encounter_id` int NOT NULL AUTO_INCREMENT,
    `encounter_type` int NOT NULL,
    `patient_id` int NOT NULL DEFAULT '0',
    `location_id` int DEFAULT NULL,
    `form_id` int DEFAULT NULL,
    `encounter_datetime` datetime NOT NULL,
    `creator` int NOT NULL DEFAULT '0',
    `date_created` datetime NOT NULL,
    `voided` tinyint(1) NOT NULL DEFAULT '0',
    `voided_by` int DEFAULT NULL,
    `date_voided` datetime DEFAULT NULL,
    `void_reason` varchar(255) DEFAULT NULL,
    `changed_by` int DEFAULT NULL,
    `date_changed` datetime DEFAULT NULL,
    `visit_id` int DEFAULT NULL,
    `uuid` char(38) NOT NULL,
    PRIMARY KEY (`encounter_id`),
    UNIQUE KEY `encounter_uuid_index` (`uuid`),
    KEY `encounter_datetime_idx` (`encounter_datetime`),
    KEY `encounter_ibfk_1` (`creator`),
    KEY `encounter_type_id` (`encounter_type`),
    KEY `encounter_form` (`form_id`),
    KEY `encounter_location` (`location_id`),
    KEY `encounter_patient` (`patient_id`),
    KEY `user_who_voided_encounter` (`voided_by`),
    KEY `encounter_changed_by` (`changed_by`),
    KEY `encounter_visit_id_fk` (`visit_id`),
    KEY `idx_encounter_visit_id_voided` (`visit_id`,`voided`),
    CONSTRAINT `encounter_changed_by` FOREIGN KEY (`changed_by`) REFERENCES `users` (`user_id`),
    CONSTRAINT `encounter_form` FOREIGN KEY (`form_id`) REFERENCES `form` (`form_id`),
    CONSTRAINT `encounter_ibfk_1` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`),
    CONSTRAINT `encounter_location` FOREIGN KEY (`location_id`) REFERENCES `location` (`location_id`),
    CONSTRAINT `encounter_patient` FOREIGN KEY (`patient_id`) REFERENCES `patient` (`patient_id`) ON UPDATE CASCADE,
    CONSTRAINT `encounter_type_id` FOREIGN KEY (`encounter_type`) REFERENCES `encounter_type` (`encounter_type_id`),
    CONSTRAINT `encounter_visit_id_fk` FOREIGN KEY (`visit_id`) REFERENCES `visit` (`visit_id`),
                             CONSTRAINT `user_who_voided_encounter` FOREIGN KEY (`voided_by`) REFERENCES `users` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb3;

SET FOREIGN_KEY_CHECKS=1;
